### PR TITLE
Fixed shuffle environment

### PR DESCRIPTION
**Pull request by XronosUF**
I fixed the shuffle environment so that it correctly pulls only the first question in the environment and suppresses the rest. It also correctly numbers other problems that follow, to avoid the suppressed problems from jumping the counter.
Still remains to implement the shuffling code from javascript.

### CODE REVIEW

**Comment by bartsnapp** [comment]
Hi,

Can you explain how it was "broken?"

To suppress the other exercises/problems/ etc, use the documentclass option
"handout"

-Bart

**Comment by XronosUF** [comment]
Hey!

The environment Shuffle was defined in the ximera.cls, but then renewed into a blank environment in ximra.4ht. This appears to be an artifact of changing over the ConfigEnv command to apply to a lot of environments (like problem, exercise, etc) and then using the same command for Shuffle, which is a fundamentally different style environment so it was being configured improperly.

As a result, the options were eliminated before they would take effect. Using the parameter [handout] in the activity document is necessary for the logic checks, but this didn't help this as the logic checks were all in the .cls file, which were eliminated by the renew environment in the 4ht file.

To fix this, I transferred over the code to the .4ht file, but when I did so the logic checks for the numbering were slightly off. Specifically they would either not number the first problem, or number the first problem as 2 and iterate from there. I adjusted them to correct for the numbering issue.

**Comment by XronosUF** [comment]
UF Syle files have been uploaded as well. There is an instruction file included, but in short the style files should support the manipulation, filtering, and permutation of very large banks of questions. 

Our current question bank is approximately 325,000 (unique) questions. Using this system we can filter and select 10 problems from the database in about 20 seconds on a typical laptop.

**Comment by bartsnapp** [comment]
I was unable to merge this without conflicts. Email me directly and maybe we can make it work.

**Pull request merged**
